TRTABSZ=64,
APPLID=(CICSTS55,CICSTS55)                APPLID CICSTS55 IS DEFAULT
AICONS=AUTO                               MVS CONSOLE SUPPORT
AUXTR=OFF                                 TURN OFF AUX TRACE
AUXTRSW=NEXT                              ROTATE TO NEXT WHEN FULL
CICSSVC=216                               SVC NUMBER FOR CICS
CPSMCONN=NO
EDSALIM=100M                              FOR PR JVM
DSALIM=7M
FEPI=YES                                  START FEPI INTERFACE
GMTEXT='WELCOME TO CICS TS 5.5'
USSHOME=/usr/lpp/cicsts/cicsts55
USSCONFIG=/usr/lpp/cicsts/cicsts55/dfhconfig
GRPLIST=(XYZLIST,GENALIST,HCAZLIST)
GTFTR=ON                                  GTF TRACE ON
IRCSTRT=NO                                DO NOT START IRC AUTOMATICALLY
ISC=NO                                    DO NOT INCLUDE ISC/MRO
INITPARM=(EQA0CPLT='NLE,STK,NWP')
KEYRING=CICSRNG
PLTPI=YES
PLTSD=SD
RLS=NO                                    NO RLS SUPPORT YET
GMTRAN=CESN
SEC=YES
XTRAN=NO
XDB2=NO
XCMD=NO
XDCT=NO
XFCT=NO
XHFS=NO
XJCT=NO
XPPT=NO
XPCT=NO
XPSB=NO
XPTKT=NO
XRES=NO
XTST=NO
XUSER=NO
SIT=6$                                    USE SUPPLIED SIT 6$
STATRCD=OFF                               RECORDS STATISTICS TO SMF
SYSIDNT=S720                              SYSIDNT IS S710
SPCTRSO=(1,2)                             TRACE ON SOCKET DOMAIN
SPCTRWB=(1,2)                             TRACE WEB INTERFACE
TCPIP=YES                                 FOR TCPIP & IIOP SERVICES
FCT=NO,
TCT=NO,
SRT=1$,                                   ADD RECOVERY
PGRET=P/,
PGPURGE=T/,
PGCOPY=C/,
PGCHAIN=X/,
DB2CONN=YES,
.END